In [1]:
import torch

In [2]:
w1 = torch.rand(5, 4)
w1.shape, w1, w1.requires_grad

(torch.Size([5, 4]),
 tensor([[0.5281, 0.0118, 0.1170, 0.8329],
         [0.4175, 0.9980, 0.5873, 0.7429],
         [0.6451, 0.6399, 0.7961, 0.1751],
         [0.3774, 0.6720, 0.4722, 0.6053],
         [0.0178, 0.9580, 0.3456, 0.3501]]),
 False)

In [3]:
w1.requires_grad_()

tensor([[0.5281, 0.0118, 0.1170, 0.8329],
        [0.4175, 0.9980, 0.5873, 0.7429],
        [0.6451, 0.6399, 0.7961, 0.1751],
        [0.3774, 0.6720, 0.4722, 0.6053],
        [0.0178, 0.9580, 0.3456, 0.3501]], requires_grad=True)

In [4]:
x = torch.rand(4, 1)
x.shape, x, x.requires_grad

(torch.Size([4, 1]),
 tensor([[0.7036],
         [0.8408],
         [0.7220],
         [0.0120]]),
 False)

In [5]:
# y = w1 * x.
y = torch.matmul(w1, x)
y, y.requires_grad

(tensor([[0.4760],
         [1.5658],
         [1.5688],
         [1.1787],
         [1.0717]], grad_fn=<MmBackward0>),
 True)

In [6]:
print(w1.grad_fn, x.grad_fn, y.grad_fn)

None None <MmBackward0 object at 0x7f162907b8e0>


In [7]:
print(w1.grad, x.grad, y.grad)

None None None


/home/rgaurav/Public/Py-Envs/Lava/lib/python3.9/site-packages/torch/_tensor.py:1083: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten/src/ATen/core/TensorBody.h:482.)
  return self._grad


In [8]:
k = y.sum()
print(k)
print(k.backward())

tensor(5.8611, grad_fn=<SumBackward0>)
None


In [9]:
print(w1.grad, x.grad, y.grad)

tensor([[0.7036, 0.8408, 0.7220, 0.0120],
        [0.7036, 0.8408, 0.7220, 0.0120],
        [0.7036, 0.8408, 0.7220, 0.0120],
        [0.7036, 0.8408, 0.7220, 0.0120],
        [0.7036, 0.8408, 0.7220, 0.0120]]) None None


# xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

In [10]:
w = torch.as_tensor(3.)
w.requires_grad_()
x = torch.as_tensor(2)
y = w*x

In [11]:
print(w.requires_grad, x.requires_grad, y.requires_grad)

True False True


In [12]:
print(w.grad, x.grad, y.grad)

None None None


In [13]:
print(y)

tensor(6., grad_fn=<MulBackward0>)


In [14]:
y.backward()

In [15]:
print(w.grad, x.grad, y.grad) # dy/dw

tensor(2.) None None


In [16]:
m = 5 * w
print(m.requires_grad, m.grad)

True None


In [17]:
m = m.detach()
print(m.requires_grad)

False


# xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

$$y = x^2 + 2$$
$$m = y\times4$$
$$l = y^2  \text{     where y is detached      } $$

In [18]:
# y = x^2 + 2
x = torch.as_tensor(3.)
x.requires_grad_()
a = torch.as_tensor(2.)
a.requires_grad_()
#y = x**2 + 2
y = x**2 + a**2
#print(x.requires_grad, y.requires_grad)
print(a.requires_grad, x.requires_grad, y.requires_grad)
print(y)

True True True
tensor(13., grad_fn=<AddBackward0>)


In [19]:
# m = y * 4
m = y*4
print(m, m.requires_grad)

tensor(52., grad_fn=<MulBackward0>) True


In [20]:
l = y.detach()**2
#l = y**2
print(l, l.requires_grad)

tensor(169.) False


In [21]:
#l.backward()
#m.backward()
#print(m.grad, l.grad, y.grad, x.grad)

In [22]:
m = y*4 + l

In [23]:
m.backward()
print(m.grad, l.grad, y.grad, x.grad)

None None None tensor(24.)


In [24]:
print(m.grad, l.grad, y.grad, x.grad, a.grad)

None None None tensor(24.) tensor(16.)


# xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

In [35]:
class Hello(object):
    def __init__(self, name):
        self._name = name
    
    def __len__(self):
        return len(self._name)
    
    def __call__(self):
        return "Hello %s" % self._name

In [37]:
Hello("Ram")()

'Hello Ram'

In [38]:
len(Hello("Ram"))

3